# webhook settings
webhook:
    # this is the "Webhook URL" under your Incoming Webhook's Integration Settings
    url:   https://hooks.slack.com/services/<therest/ofthe/path>

    # whether or not to automatically unfurl links in slack; links such as
    # youtube/twitter/flicker/xkcd will do unfurl regardless of the setting
    unfurl_links: "true"

# irc settings
channel:
    # channel mapping - text from the specified irc channel will get pushed to the corresponding slack channel;
    # works with public channels and private groups and does not matter if you prefix the slack channel with #
    mapping:
        # format: <irc_channel>: <slack_channel>
        "#lounge": "#general"
        "#random": "#random"
        "#secret": "myprivategroup"

    # prefixes for bot commands that will not be echoed to slack; for instance, if you set 
    # a command prefix of "!c", then "!test" will be pushed to slack but "!cmd" will not
    # leave blank to echo all messages to slack
    command_prefix: "!"